# Schema de informações passadas dos usuários logados
type AuthInfo {
  authorization: ID!
  privileges: [String!]!
  email: String!
  username: String!
  token: String!
  name: String!
  signature: String!
}

# Schema de informações dos usuários

type Location {
  street: String!
  number: Int!
  complement: String!
  district: String!
  state: String!
  city: String!
  zipcode: String!
}

type UserInfo {
  authorization: String!
  privileges: [String!]!
  photoProfile: String!
  username: String!
  email: String!
  name: String!
  surname: String!
  cnpj: String!
  location: Location!
}

type Query {
  """
  Efetua o login do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-query?id=authlogin
  """
  authLogin(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Senha do usuário
    """
    pwd: String!
    """
    Código da verificação de duas etapas
    """
    twofactortoken: String
  ): AuthInfo!
    @auth(
      keys: ["SweteNlPut4uqlBiwIchiXafe1ld1bRICriBra7iPRazOs0ItRAtiwriyoyuyo-u"]
    )
    @encodeuri(method: "lz-string")
  """
  Efetua o logout do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-query?id=authlogout
  """
  authLogout(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Token exclusivo de segurança da solicitação
    """
    token: String!
  ): Boolean!
    @auth(
      keys: ["vlta#eke08uf=48uCuFustLr3ChL9a1*wrE_ayi0L*oFl-UHidlST8moj9f8C5L4"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Verifica se o token de segurança do usuário está expirado
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-query?id=authexpired
  """
  authExpired(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Token exclusivo de segurança da solicitação
    """
    token: String!
  ): Boolean!
    @auth(
      keys: ["5wEvlBR8TRuxePL42thecuv8sP3Pe4lB56EzLBra9Iph9WiPRId3ONL20uK7T#Ip"]
    )
    @encodeuri(method: "lz-string")
  """
  Verifica se o token de segurança do usuário está valido
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-query?id=authvalidate
  """
  authValidate(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Token exclusivo de segurança da solicitação
    """
    token: String!
    """
    Assinatura do token
    """
    signature: String!
  ): Boolean!
    @auth(
      keys: ["4VMYcqF77yRfA9dmzVcD9JPZFycmN5dZdtDZww49ENHW4H97nY7RuzWa6jTkAMY3"]
    )
    @encodeuri(method: "lz-string")
  """
  Envia o e-mail de confirmação da conta do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-query?id=emailresendconfirm
  """
  emailResendConfirm(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
  ): Boolean!
    @auth(
      keys: ["p4YIfr$zoG9buqUD0Ochodu1enex2ZOCh8Y1C8beMlDIbrIqU4OThLsTe6LMEB@+"]
    )
    @encodeuri(method: "lz-string")
  """
  Retorna as informações do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-query?id=getuserinfo
  """
  getUserInfo(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
  ): UserInfo!
    @auth(
      keys: ["NoZjIRxH*miT4xs!$sR&oOdBxk6*1x!lcXDDwf#d!XuJ#hyHAVpIFrnAI@T9pIFr"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
}

type Mutation {
  """
  Registra um novo usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=registeruser
  """
  registerUser(
    """
    Autorização exclusiva do usuário para entrar no portal
    """
    authorization: String!
    """
    Privilégios do usuário
    Suporta: ["common", "administrador", "supervisor", "moderador"]
    """
    privileges: [String!]!
    """
    Arquivo da foto de perfil do usuário
    Padrão: [filename].[extension]
    """
    photoProfile: String
    """
    Nome do usuário
    """
    username: String!
    """
    Senha do usuário
    """
    password: String!
    """
    Primeiro nome do usuário
    """
    name: String!
    """
    Último nome do usuário
    """
    surname: String!
    """
    Endereço de e-mail do usuário
    """
    email: String!
    """
    CPF/CNPJ do usuário
    Padrão: 99999999999
    """
    cnpj: String!
    """
    Propriedades do endereço do usuário
    Padrão: ["street", "number", "complement", "district", "state", "city", "zipcode"]
    """
    location: [String!]!
  ): String!
    @auth(
      keys: ["brufiT87+uchUfI9eFlPhificRi+OzawIwrIfriTH2Fr0ke0&fodrispl8Lc0IZo"]
    )
    @encodeuri(method: "lz-string")
  """
  Atualiza os dados do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=updatedata
  """
  updateData(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Endereço de e-mail do usuário
    """
    email: String!
    """
    Nome do usuário
    """
    username: String!
    """
    Primeiro nome do usuário
    """
    name: String!
    """
    Último nome do usuário
    """
    surname: String!
    """
    CPF/CNPJ do usuário
    Padrão: 99999999999
    """
    cnpj: String!
    """
    Propriedades do endereço do usuário
    Padrão: ["street", "number", "complement", "district", "state", "city", "zipcode"]
    """
    location: [String!]!
  ): Boolean!
    @auth(
      keys: ["OGh!pb@lX*fnElqYo8%#VO63KihIr$F1nhf!a@SFOB7$VeQ0*R+s!Sd8wqewq4eq"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Atualiza a foto de perfil do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=updatephotoprofile
  """
  updatePhotoProfile(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Arquivo da foto de perfil do usuário
    Padrão: [filename].[extension]
    """
    photo: String!
  ): Boolean!
    @auth(
      keys: ["GHbqjX-RMmbKMbCfGZBV*xF48Lzqg74vq8G6eM3KTekCdaV3JZ+MYDz=RyGeWJ8N"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Altera a senha do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=changepassword
  """
  changePassword(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Senha atual do usuário
    """
    pwd: String!
    """
    Nova senha do usuário
    """
    new_pwd: String!
  ): String!
    @auth(
      keys: ["Re94FUC3phicraR94Tuq5@0Sto16sp4swa7I1As5uChEmUhExuvATrovic5lfic"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Gera um QRCode para ativação da verificação de duas etapas da conta do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=authsigntwofactor
  """
  authSignTwofactor(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
  ): String!
    @auth(
      keys: ["bu9Tix&1amuqihiXeHa*ajucRav6b5p7frOTRan6BLn!R27Wo*rlNA?Huf38riKo"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Verifica o código da verificação de duas etapas da conta do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=authverifytwofactor
  """
  authVerifyTwofactor(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
    """
    Código da verificação de duas etapas
    """
    qrcode: String!
  ): Boolean!
    @auth(
      keys: ["duhoHU4o#3!oCHogLw*6WUbrE2radr2CrlpLD+P7Ka*R-veSEB75lsT6PeblPuko"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Ativa a verificação de duas etapas da conta do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=authenabledtwofactor
  """
  authEnabledTwofactor(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
  ): String!
    @auth(
      keys: ["TH6021Mufr&0$B&?&-op&i-L-6p4ATH31h+?*m&dRACAc7e0Osw9$4E3oWRawE8h"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Desativa a verificação de duas etapas da conta do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=authdisabletwofactor
  """
  authDisableTwofactor(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
  ): String!
    @auth(
      keys: ["ciy16pAfawUfe5riwro1lth7barucOgavlprIbrlcrLVikekiPhapr*proDatrOr"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Recuperação da conta, caso perca o gerador de códigos para a verificação de duas etapas da conta do usuário
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/users-mutations?id=authretrievetwofactor
  """
  authRetrieveTwofactor(
    """
    Autorização exclusiva do usuário
    """
    auth: String!
  ): String!
    @auth(
      keys: ["nlyachaglswisifrufrod0stEpec@UwlvizestAtr1xajanegaswa@remopheWip"]
    )
    @encodeuri(method: "lz-string")
}

directive @auth(keys: [String!]!) on FIELD_DEFINITION

directive @token(ignore: Boolean!) on FIELD_DEFINITION

directive @privilege(keys: [String!]!) on FIELD_DEFINITION

directive @encodeuri(method: String!) on FIELD_DEFINITION
