# Schema de uploads
scalar Upload

type UploadFIle {
  authorId: String!
  name: String!
  size: Int!
  compressedSize: Int!
  fileId: String!
  version: Int!
  status: String!
}

type Mutation {
  singleUpload(
    file: Upload!
    size: String!
    signedUrl: String!
    auth: String!
    randomName: Boolean!
  ): UploadFIle!
  multipleUpload(
    files: [Upload!]!
    sizes: [String!]!
    signedUrl: String!
    auth: String!
    randomName: Boolean!
  ): [UploadFIle!]!
}
