# Schema de tipo para as pastas

type Folder {
  cid: String
  authorId: String
  name: String
  description: String
  status: String
  type: String
  tag: String
  filesId: [String]
  foldersId: [String]
}

# Schema de input para as pastas

input FolderFilter {
  cid: String
  authorId: String
  name: String
  description: String
  status: String
  type: String
  tag: String
}

type Query {
  """
  Efetua a busca da pasta
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/folders-query?id=folderget
  """
  folderGet(
    """
    Filtro usado para buscar o conjunto de pastas no MongoDB
    """
    filter: FolderFilter,
    """
    Pula x itens iniciais antes de iniciar a busca no banco de dados
    """
    skip: Int,
    """
    Limite de pastas a serem retornadas
    """
    limit: Int
  ): [Folder]!
    @auth(
      keys: ["guI{rrKJGtc8{/4po.fd<rt48s]Lg_CXd$-?.3}g;_N<T(]Grw97.jczDR?>gy&]"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
}

directive @auth(keys: [String!]!) on FIELD_DEFINITION

directive @token(ignore: Boolean!) on FIELD_DEFINITION

directive @encodeuri(method: String!) on FIELD_DEFINITION