# Schema de input para os vCards
input input_file {
  id: String!
  name: String!
  type: String!
}

input input_birthday {
  year: Int!
  month: Int!
  day: Int!
}

input input_socialURL {
  media: String!
  url: String!
}

input input_socialmedia {
  name: String!
  value: String!
  enabled: Boolean!
}

input input_whatsapp {
  phone: String!
  text: String!
  message: String!
}

input input_cardFooter {
  email: String!
  location: String!
  website: String!
  attachment: input_file!
  socialmedia: [input_socialmedia!]!
}

input input_vcardmetadavalues {
  path: String!
  name: String!
  type: String!
}

input input_vcardmetadata {
  file: input_vcardmetadavalues!
  logotipo: input_vcardmetadavalues!
  photo: input_vcardmetadavalues!
}

input input_vcard {
  firstname: String!
  lastname: String!
  organization: String!
  photo: input_file!
  logo: input_file!
  workPhone: [String!]!
  birthday: input_birthday!
  title: String!
  url: String!
  workUrl: String!
  email: String!
  label: String!
  countryRegion: String!
  street: String!
  city: String!
  stateProvince: String!
  postalCode: String!
  socialUrls: [input_socialURL!]!
  metadata: input_vcardmetadata
}

input input_card {
  id: String
  version: String!
  photo: input_file!
  name: String!
  jobtitle: String!
  phones: [String!]!
  whatsapp: input_whatsapp!
  vcard: input_vcard!
  footer: input_cardFooter!
}

type CardInfo {
  index: String
  cid: String
  version: String
  photo: Photo
  name: String
  jobtitle: String
  phones: [String]
  whatsapp: Whatsapp
  vcard: VCard
  footer: Footer
  createdAt: String
}

type Photo {
  name: String
  type: String
  id: String
}

type Whatsapp {
  phone: String
  text: String
  message: String
}

type VCard {
  firstname: String
  lastname: String
  organization: String
  photo: Photo
  logo: Photo
  workPhone: [String]
  birthday: Birthday
  title: String
  url: String
  workUrl: String
  email: String
  label: String
  countryRegion: String
  street: String
  city: String
  stateProvince: String
  postalCode: String
  socialUrls: [SocialUrls]
  metadata: VCardMetadata
}

type Birthday {
  year: Int
  month: Int
  day: Int
}

type SocialURL {
  media: String
  url: String
}

type File {
  name: String
  type: String
  id: String
}

type SocialUrls {
  media: String
  url: String
}

type Footer {
  email: String
  location: String
  website: String
  attachment: Photo
  socialmedia: [Socialmedia]
}

type Socialmedia {
  name: String
  value: String
}

type VCardMetadataValues {
  path: String!
  name: String!
  type: String!
}

type VCardMetadata {
  file: VCardMetadataValues!
  logotipo: VCardMetadataValues!
  photo: VCardMetadataValues!
}

type Query {
  """
  Retorna uma lista de cartões digitais
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/cards-query?id=cardget
  """
  getCards(
    """
    ID usado como base para que a lista retorne cartões com ID's mais recentes
    """
    lastIndex: String
    """
    Limite de cartões a serem retornados na lista
    """
    limit: Int!
  ): [CardInfo!]!
    @auth(
      keys: ["H6uagjXejR8GcjFAxPtCNqtWShxXaEmXJ89c5ZrgczsD7VAaDZr5GydYKadHtUQc"]
    )
  """
  Busca por um cartão digital
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/cards-query?id=cardget
  """
  findCard(
    """
    ID do cartão digital a ser retornado
    """
    cid: String!
  ): [CardInfo!]!
    @auth(
      keys: ["H6uagjXejR8GcjFAxPtCNqtWShxXaEmXJ89c5ZrgczsD7VAaDZr5GydYKadHtUQc"]
    )
}

type Mutation {
  """
  Cria um novo vcard
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/cards-mutations?id=vcardcreate
  """
  vcardCreate(
    """
    Propriedades do vcard
    """
    data: input_vcard!
  ): VCardMetadata!
    @auth(
      keys: ["fA=ireb506d@lgAdA9&OfaSawro?a_11rajo_+dud@uph_k1gasweprut-owr+br"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Cria um novo cartão digital
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/cards-mutations?id=cardcreate
  """
  cardCreate(
    """
    Propriedades do cartão digital
    """
    data: input_card!
  ): String!
    @auth(
      keys: ["6T9YEPuTRu3e0aQevEdeVA8r1Dr&8RAFReSud0&Huhld54F*E#==E*OBr2&h1wEC"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Atualiza um cartão digital
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/cards-mutations?id=cardupdate
  """
  cardUpdate(
    """
    Propriedades do cartão digital
    """
    data: input_card!
  ): String!
    @auth(
      keys: ["ji4H@Dr8MU*R@CramlVuyEFR9YiSlP1=veZ_7aFrUS$uFrAZomAs=ENi9I8oFasT"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
  """
  Remove um cartão digital
  Docs: https://grupomavedigital-wiki.vercel.app/#/graphql/cards-mutations?id=cardremove
  """
  cardRemove(
    """
    ID do cartão digital
    """
    id: String!
  ): Boolean!
    @auth(
      keys: ["fRiphl8pus!uspEdr-zisepip1Uv63pucradisTeswEfru5LthIbr5rlv3dRosuv"]
    )
    @token(ignore: false)
    @encodeuri(method: "lz-string")
}

directive @auth(keys: [String!]!) on FIELD_DEFINITION

directive @token(ignore: Boolean!) on FIELD_DEFINITION

directive @encodeuri(method: String!) on FIELD_DEFINITION
